from backend.exception.base_stackable_exception import StackableException


class UnexpectedException(StackableException):
    pass
